---
title: "Collaborative Data Science Project"
author: "Jamie Wiener, Ryan Hernandez, and Claire Brandes"
output: 
  html_document: 
    highlight: tango

---

Loading necessary packages:

```{r message=FALSE}
library(tidyverse)
```

Loading in dataset: census data of tree species in Panama 

```{r message=FALSE}
f <- "https://raw.githubusercontent.com/clairebran/collaborative-project-ADA/main/bci_census_2010.txt"

d <- read_tsv(f)
```

Formatting census dataset with species names and number of individuals of each species present:

```{r}
census <- function(col_name){
 
  species_names <- list()
  species_names <- unique(col_name)
  
  individuals <- vector()
  for (i in 1:length(species_names)){
  individuals[[i]] <- length(which(col_name == species_names[[i]]))
  }
  
  census <- data.frame(species_names, individuals)
return(census)
  }
  
c <- census(d$Latin)
```

Functions for calculating species richness, Simpson's Diversity Index, Simpson Evenness, Shannon-Wiener Index (and Hmax), Shannon Evenness, and Berger-Parker Dominance: 

```{r}
div_index <- function(species_col, pop_col){
  
  index_name <- c("Species Richness", "Simpson's Index", "Simpson's Evenness", "Shannon-Weiner Index", "Shannon Hmax", "Shannon's Evenness", "Berger-Parker Index")
  index_values <- vector()
  
  simps_ind <- vector()
  shannon_ind <- vector()
  berger_ind <- vector()
  
  num_spe <- length(c$species_names)
  tot_pop <- sum(pop_col)
  
  #Species Richness
  index_values[[1]] <- num_spe
  
  #Simpson's Diversity Index 
  for (i in 1:length(species_col)){
  simps_ind[[i]] <- (pop_col[[i]]/tot_pop)^2
  index_values[[2]] <- sum(simps_ind)
  }
  
  #Simpson's Evenness
  index_values[[3]] <- 1/(index_values[[2]]*num_spe)
  
  #Shannon-Wiener Diversity Index and Hmax
  for (i in 1:length(species_col)){
  shannon_ind[[i]] <- (pop_col[[i]]/tot_pop)*log(pop_col[[i]]/tot_pop)
  index_values[[4]] <- sum(shannon_ind)*-1
  index_values[[5]] <- log(num_spe)
  }
  
  #Shannon's Evenness
  index_values[[6]] <- (index_values[[4]]/index_values[[5]])
  
  #Berger-Parker Dominance
  for (i in 1:length(species_col)){
  berger_ind[[i]] <- (pop_col[[i]]/tot_pop)
  index_values[[7]] <- max(berger_ind)
  }
  
  index_values <- format(index_values, scientific = FALSE)
  div_index <- data.frame(index_name, index_values)
  return(div_index)
  }

div_ind <- div_index(c$species_names, c$individuals)
```


